SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.2
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_ROTATION_SPEED = 50
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 2500
PLAYER_SHOT_COOLDOWN = 0.5
PLAYER_LIVES = 3
INVINCIBILITY_DURATION = 3.0
ASTEROID_EDGE_SPAWN_OFFSET = 200 
